version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad

  - package-ecosystem: npm
    directory: '/package/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      cdk-lambda:
        patterns:
          - 'aws-cdk*'
          - '@aws-cdk/*'
          - '@aws-lambda-powertools/*'
          - '@middy/*'
          - '@swc/*'
          - 'constructs'
          - 'esbuild'
          - 'regenerator-runtime'
          - 'source-map-support'
          - 'ts-node'
      eslint-prettier:
        patterns:
          - '@typescript-eslint/*'
          - 'eslint'
          - 'eslint-*'
          - 'prettier'

  - package-ecosystem: npm
    directory: '/example/cdk/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      cdk-lambda:
        patterns:
          - 'aws-cdk*'
          - '@aws-cdk/*'
          - '@swc/*'
          - 'constructs'
          - 'esbuild'
          - 'regenerator-runtime'
          - 'source-map-support'
          - 'ts-node'
      eslint-prettier:
        patterns:
          - '@typescript-eslint/*'
          - 'eslint'
          - 'eslint-*'
          - 'prettier'

  - package-ecosystem: npm
    directory: '/example/app/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      nextjs:
        patterns:
          - 'next'
          - '@next/*'
          - 'eslint-config-next'
      eslint-prettier:
        patterns:
          - '@typescript-eslint/*'
          - 'eslint'
          - 'eslint-*'
          - 'prettier'
        exclude-patterns:
          - 'eslint-config-next'
