autoInstallPeers: true

enablePrePostScripts: true

onlyBuiltDependencies:
  - sharp
  - unrs-resolver

strictPeerDependencies: false

overrides: 
  "@types/react": 19.2.2
  "@types/react-dom": 19.2.2
    
